env: add firebase initial settings

diff --git a/.github/workflows/frontend-deploy.yml b/.github/workflows/frontend-deploy.yml
--- a/.github/workflows/frontend-deploy.yml
+++ b/.github/workflows/frontend-deploy.yml
@@ -74,12 +74,27 @@ jobs:
             exit 1
           fi
 
-      - name: Require Google OAuth client ID
+      - name: Require Firebase Authenticate Variables
         env:
-          PUBLIC_GOOGLE_OAUTH_CLIENT_ID: ${{ vars.GOOGLE_OAUTH_CLIENT_ID }}
+          PUBLIC_FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
+          PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
+          PUBLIC_FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
+          PUBLIC_FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
         run: |
-          if [ -z "$PUBLIC_GOOGLE_OAUTH_CLIENT_ID" ]; then
-            echo "::error::GOOGLE_OAUTH_CLIENT_ID repository variable must be set before deployment."
+          if [ -z "$PUBLIC_FIREBASE_API_KEY" ]; then
+            echo "::error::PUBLIC_FIREBASE_API_KEY repository variable must be set before deployment."
+            exit 1
+          fi
+          if [ -z "$PUBLIC_FIREBASE_AUTH_DOMAIN" ]; then
+            echo "::error::PUBLIC_FIREBASE_AUTH_DOMAIN repository variable must be set before deployment."
+            exit 1
+          fi
+          if [ -z "$PUBLIC_FIREBASE_PROJECT_ID" ]; then
+            echo "::error::PPUBLIC_FIREBASE_PROJECT_ID repository variable must be set before deployment."
+            exit 1
+          fi
+          if [ -z "$PUBLIC_FIREBASE_APP_ID" ]; then
+            echo "::error::PUBLIC_FIREBASE_APP_ID repository variable must be set before deployment."
             exit 1
           fi
 
@@ -87,7 +102,10 @@ jobs:
         env:
           PUBLIC_API_BASE_PATH: ${{ vars.PUBLIC_API_BASE_PATH }}
           CLOUDFLARE_WEB_ANALYTICS_TOKEN: ${{ vars.CLOUDFLARE_WEB_ANALYTICS_TOKEN }}
-          PUBLIC_GOOGLE_OAUTH_CLIENT_ID: ${{ vars.GOOGLE_OAUTH_CLIENT_ID }}
+          PUBLIC_FIREBASE_API_KEY: ${{ vars.FIREBASE_API_KEY }}
+          PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ vars.FIREBASE_AUTH_DOMAIN }}
+          PUBLIC_FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
+          PUBLIC_FIREBASE_APP_ID: ${{ vars.FIREBASE_APP_ID }}
         run: npm --workspace=@neon-underrealm/frontend run build:public
 
       - name: Build search index
